[TK-13]: Logic for create an account
Vape-X/Vape-X pull request #15
Opened 2022-09-30 01:13 UTC by AbdulsKhan1

## Jira: [TK-13](https://shop-go.atlassian.net/browse/TK-13?atlOrigin=eyJpIjoiYTY1MjUyMDhhMjFmNDQ4YjgwMThjNTZhZDdiM2Y5MDYiLCJwIjoiaiJ9)

**Description**:
- Restrict the user to enter more than 6 letters in password, password should be secure entry text, should not be visible all the time & password must have a special character and a number and no emoji.
- Add tap to dismiss in the screen to dismiss the keyboard & this screen should be scrollable, so that keyboard doesn't cover the button and text.
- Keep the next button disabled until user fills all the information 
- The email must have a valid format such as "johndoe@gmail.com"

**How to test it?**
- run the app on simulator and fill all text field
- password required special character and a number 
- email required "@" and ".co"

## Screenshots&Gifs:
<img src="https://user-images.githubusercontent.com/113795132/193168588-74b581ac-c886-4b55-8597-8bcd28174fff.gif" width=30% height=30%>

2022-09-30 01:42 UTC, basitalich requested changes

2022-09-30 01:42 UTC, basitalich commented on Vape-X/CreateAccountController.swift
> +
Move this to a seperate file

2022-09-30 02:35 UTC, haroonmaqsoodch commented on Vape-X/CreateAccountController.swift
>      @IBOutlet weak var passwordTextfield: UITextField!
It's better to write Textfield after the property name, also fix the spellings of password

2022-09-30 02:43 UTC, haroonmaqsoodch approved these changes

2022-10-01 22:40 UTC, AbdulsKhan1 commented on Vape-X/CreateAccountController.swift
> +
fixed.

2022-10-01 22:41 UTC, AbdulsKhan1 commented on Vape-X/CreateAccountController.swift
>      @IBOutlet weak var passwordTextfield: UITextField!
fixed.

2022-10-05 00:27 UTC, ammadahmed22 requested changes
where is username validation

2022-10-05 00:51 UTC, ammadahmed22 reviewed
disable emojis

2022-10-06 01:00 UTC, ammadahmed22 approved these changes
lgtm

2022-10-07 08:02 UTC, closed without merging