[TK-12]: Logic for login
Vape-X/Vape-X pull request #16
Opened 2022-09-30 03:44 UTC by bilalnaeem9

## Jira: [TK-12](https://shop-go.atlassian.net/browse/TK-12?atlOrigin=eyJpIjoiNDIxMTdmODM3NmIyNGUzYmIxODdjMDE1NmVkYjcxMTIiLCJwIjoiaiJ9)

**Description**:
- password validation implemented as well as no emojis in password
- password length fixed to min of 6 along with 1 special character and 1 number
- textfield animation added(shake left/right and boarder red) for wrong password
- secure password implement

**How to test it?**
- password with no requirement triggers animation

## Screenshots&Gifs:
<img src="https://user-images.githubusercontent.com/113795830/193184065-2eb0f84f-5512-4149-8d72-2a1dd707cc14.png" width=30% height=30%>

<img src="https://user-images.githubusercontent.com/113795830/193184219-e4503c8f-a963-4c3b-9565-2dab57d3329d.png" width=30% height=30%>

2022-10-01 18:55 UTC, Annas90 submitted a review, later dismissed

2022-10-01 19:13 UTC, haroonmaqsoodch reviewed
create a mock username and password to test the logic

2022-10-04 02:47 UTC, ammadahmed22 reviewed
after entering the test credential and touching the Login button, the keyboard doesn't dismiss.

2022-10-04 23:51 UTC, ammadahmed22 reviewed
where is the username validation (like password validation )

2022-10-05 00:12 UTC, ammadahmed22 requested changes
where is the username validation (like password validation )

2022-10-05 00:12 UTC, ammadahmed22 commented on Vape-X/LoginViewController.swift
> +    }
make a func so when the username and password are wrong or right the textfield is reset (empty).

2022-10-06 00:49 UTC, bilalnaeem9 commented on Vape-X/LoginViewController.swift
> +extension UITextField {
resolved issue.

2022-10-06 00:49 UTC, bilalnaeem9 commented on Vape-X/LoginViewController.swift
> +extension UITextField {
resolved issue.

2022-10-06 00:49 UTC, bilalnaeem9 commented on Vape-X/LoginViewController.swift
> +                txtfieldUsername.layer.borderColor = UIColor.red.cgColor
resolved issue.

2022-10-06 00:49 UTC, bilalnaeem9 commented on Vape-X/LoginViewController.swift
> +                txtfieldUsername.layer.borderColor = UIColor.red.cgColor
resolved issue.

2022-10-06 00:50 UTC, bilalnaeem9 commented on Vape-X/LoginViewController.swift
> +            if passwordText.validPassword() {
resolved issue.

2022-10-06 00:50 UTC, bilalnaeem9 commented on Vape-X/LoginViewController.swift
> +
resolved issue.

2022-10-06 00:50 UTC, bilalnaeem9 commented on Vape-X/LoginViewController.swift
> +    }
resolved issue.

2022-10-06 01:08 UTC, ammadahmed22 commented on Vape-X/ValideteViewController.swift
> +import Foundation
What is this file?

2022-10-06 01:18 UTC, ammadahmed22 commented on Vape-X/LoginViewController.swift
> +    }
You can combine this func and the one below (checkMocUserAndPassword)

2022-10-06 03:03 UTC, bilalnaeem9 commented on Vape-X/ValideteViewController.swift
> +import Foundation
this file is for extentions.

2022-10-06 03:03 UTC, bilalnaeem9 commented on Vape-X/LoginViewController.swift
> +    }
resolve issue.

2022-10-06 03:03 UTC, bilalnaeem9 commented on Vape-X/LoginViewController.swift
> +    }
resolve issue.

2022-10-06 23:17 UTC, ammadahmed22 commented on Vape-X/ValideteViewController.swift
> +import Foundation
Your file for an extension is called LoginValidateExtention this is an empty file called ValideteViewController

2022-10-07 08:28 UTC, closed without merging