[TK-9]: otp screen ui
Vape-X/Vape-X pull request #7
Opened 2022-09-22 01:18 UTC by AbdulsKhan1

Its Huzaifa Testing something

2022-09-22 01:47 UTC, basitalich requested changes

2022-09-22 19:22 UTC, haroonmaqsoodch commented on Vape-X/OTPScreenViewController.swift
> +        }else if text?.count == 0 {
space before else

2022-09-22 19:23 UTC, haroonmaqsoodch commented on Vape-X/OTPScreenViewController.swift
> +            }
one space after curly brace

2022-09-22 20:09 UTC, AbdulsKhan1 commented on Vape-X/OTPScreenViewController.swift
> +        //hello
fixed.

2022-09-22 20:09 UTC, AbdulsKhan1 commented on Vape-X/OTPScreenViewController.swift
> +        if text?.count == 1{
fixed.

2022-09-22 20:50 UTC, AbdulsKhan1 commented on Vape-X/OTPScreenViewController.swift
> +            switch textField{
fixed.

2022-09-22 20:51 UTC, AbdulsKhan1 commented on Vape-X/OTPScreenViewController.swift
> +            case OTPFirstTextField:
fixed.

2022-09-22 20:51 UTC, AbdulsKhan1 commented on Vape-X/OTPScreenViewController.swift
> +        OTPFirstTextField.addTarget(self, action: #selector(textDidChange), for: .editingChanged)
fixed.

2022-09-22 20:51 UTC, AbdulsKhan1 commented on Vape-X/OTPScreenViewController.swift
> +        }else if text?.count == 0 {
fixed

2022-09-22 20:51 UTC, AbdulsKhan1 commented on Vape-X/OTPScreenViewController.swift
> +            }
fixed.

2022-09-22 23:55 UTC, AbdulsKhan1 commented on Vape-X/Base.lproj/Main.storyboard
> -        <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="13104.12"/>
this change was made after the recent pull this is not my change.

2022-09-24 01:02 UTC, ammadahmed22 approved these changes
LGTM

2022-09-24 04:09 UTC, Annas90 commented on Vape-X/Base.lproj/Main.storyboard
> -        <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="13104.12"/>
where is the vapes picture

2022-09-27 00:56 UTC, merged